version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0
  heroku: circleci/heroku@2.0.0

executors:
  ruby-postgres:
    docker:
      - image: cimg/ruby:3.3.3
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:password@localhost:5432/delivery_route_app_test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: delivery_route_app_test

jobs:
  rspec:
    executor: ruby-postgres
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/test-results/rspec/results.xml
      - store_test_results:
          path: ~/test-results

  rubocop:
    docker:
      - image: cimg/ruby:3.3.3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run RuboCop
          command: bundle exec rubocop

  heroku_deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git main

workflows:
  build_and_deploy:
    jobs:
      - rspec
      - rubocop
      - heroku_deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: main
